sudo: false
language: generic

matrix:
  include:
    - compiler: "GHC+Stack (OSX)"
      os: osx
      addons: {apt: {packages: [libgc-dev, libgmp-dev]}}
    - compiler: "GHC+Stack (Linux)"
      addons: {apt: {packages: [libgc-dev, libgmp-dev]}}

before_install:
# stack
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ ! -f $HOME/.local/bin/stack ]; then
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C $HOME/.local/bin
    else
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
    fi
  fi

- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install llvm bdw-gc
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export SIXTEN_ARGS="--llvm-config=$(brew --prefix llvm)/bin/llvm-config"
  else
    export SIXTEN_ARGS=""
  fi

- export STACK_FLAGS='-j 2 --no-terminal --skip-ghc-check'
- stack ${STACK_FLAGS} setup

script:
- stack ${STACK_FLAGS} test --test-arguments "--catch-stderr --sixten-args \"$SIXTEN_ARGS\""
- stack ${STACK_FLAGS} test --test-arguments "--catch-stderr --sixten-args \"-O2 $SIXTEN_ARGS\""

cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/.local/bin"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  # Allow more time for new caches to be uploaded
  timeout: 1000
