resolver: lts-13.14
packages:
- '.'
extra-deps:
- llvm-hs-pretty-0.6.1.0
- parsix-0.2.0.0
- git: https://github.com/ollef/deriving-gcompare.git
  commit: 6d26b859fce3fcae181bde4c8d1b3a6d98e26068
- git: https://github.com/ollef/rock.git
  commit: f6c02b1e638f40586a5d61db0b25147db53fbd9f
